### ISSUE TITLE
KerML Symbol/Keyword pair ambiguity

### ISSUE THREAD

**Issue by emanuelpalm** [Systems-Modeling/SysML-v2-Release#11]
In Section `7.1.2.8 Symbols` of the [Part 1 - Kernel Modeling Language (KerML)](https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/1-Kernel_Modeling_Language_(KerML).pdf) document, there is a table (Table 2) listing various symbols that are interchangeable with specific keywords. The symbol `:>` is associated both with the `specializes` and the `subsets` keywords. Am I supposed to interpret this as if `specializes`, `subsets` and `:>` are all interchangeable, or is there an error in the document?

**Comment by seidewitz** [comment]
The symbol `:>` may be used interchangeably with either the keyword **`specializes`** or the keyword **`subsets`**. But this does _not_ imply that `specializes` and `subsets` can be used interchangeably with each other. That is why there are different terminal symbols SPECIALIZES and SUBSETS for the pairs `:>` / **`specializes`** and `:>` / **`subsets`**, respectively. Where SPECIALIZES is used in the syntactic grammar, either `:>` or **`specializes`** are allowed. But, when SUBSETS is used, only `:>` or **`subsets`** are allowed.

**Comment by emanuelpalm** [comment]
@seidewitz That makes things much more clear! Could this behavior be more clearly documented in the specification? Thank you.
