### ISSUE TITLE
KerML complete list of symbols

### ISSUE THREAD

**Issue by emanuelpalm** [Systems-Modeling/SysML-v2-Release#12]
In Section `7.1.2.7 Reserved Words` of the [Part 1 - Kernel Modeling Language (KerML)](https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/1-Kernel_Modeling_Language_(KerML).pdf) document, there is a list of all reserved words used by the various productions of the KerML language.

Why is there no equivalent list of symbols in Section `7.1.2.8 Symbols`?

Having a list already in Section `7.1.2` would save those wishing to implement a lexer for KerML a bit of trouble. :)

**Comment by seidewitz** [comment]
The list of symbols is simply harder to extract from our implementation right now than the list of keywords. However, such a list will be included in the specification eventually, certainly by the time of the revised submission to OMG in August, hopefully sooner.

**Comment by emanuelpalm** [comment]
@seidewitz Thank you for the clarification.
