### ISSUE TITLE
Add escape character /r to the table 1 in Kernel doc

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#13]
The escape character /r is used in the definition of SINGLE_LINE_NOTE in the section Notes and comments of the document 1-Kernel_Modeling_Language_(KerML).pdf.

However, it is not defined formally in the Table 1. Escape Sequences in the same document. 

A line should be added in Table 1.
          /r               CARRIAGE RETURN

**Comment by seidewitz** [comment]
The latest version of the draft KerML specification does not use \r in the definition of SINGLE_LINE_NOTE. See [Kernel Modeling Language](https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/1-Kernel_Modeling_Language.pdf), subclause 7.1.2.3.

**Comment by domroy** [comment]
Sorry, I missed an update.

**Comment by seidewitz** [comment]
No problem! 🙂
