### ISSUE TITLE
Membership concrete syntax in KERML doc

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#14]
In section 7.2.4.2.2 Namespace Bodies, of the KERML doc, the second item looks like this:

NamespaceMember (n : Namespace) : Membership
( ownedRelationship += PrefixDocumentation )*
( visibility = BasicVisibilityIndicator )?
( NonFeatureNamespaceMember(this, n)
| FeatureNamespaceMember(this) )

The symbol 'equals' ('=') seems lacking at the end of the first line of this concrete syntax.

**Comment by seidewitz** [comment]
Fixed for 2021-05 release.
