### ISSUE TITLE
Wrong namespace in the example for Namespace Bodies in KERML doc

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#15]
In section 7.2.4.2.2 Namespace Bodies, of the KERML doc, in the middle of page 51, there is an example of the owned comments

namespace N5 {
  class A;
  comment Comment1 about A
  /* This is a comment about class A. */
  comment Comment 2
  /* This is a comment about namespace N3. */
  /* This is also a comment about namespace N3. */
}

The last two comments should refer to N5 instead of N3.

**Comment by seidewitz** [comment]
Fixed for the 2021-05 release.
