### ISSUE TITLE
Reserved words in KerML

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#16]
The following keywords mentioned in KerML doc are not identified as reserved keywords in section 7.1.2.7 Reserved Words

featuring
is
namespace
struct

The following keywords mentioned in the SysML doc are not identified as reserved keywords. This notion of reserved keywords is not mentioned in the SysML doc. I'm not sure they should be. The real question is : Can a name be one of those keywords? Here is a rapid list:

attribute
bind
connection
def
dependency
enum
individual
interface
item
part
ref
snapshot
timeslice
value
variation

**Comment by seidewitz** [comment]
The list of KerML reserved words has been updated for the 2021-05 release.

The SysML keywords you listed, among several others, are, in fact, reserved words. They cannot be used as identifiers. However, they _can_ be used as element names if surrounded by single quotes (as can reserved words in KerML). For example, in the SysML textual notation, `attribute` cannot be used as an identifier to name an element, but `'attribute'` can be used to give an element the name "attribute".

The complete list of reserved words for SysML will be included in a future draft of the SysML v2 spec.

**Comment by jbouvier-onshape** [comment]
Just another comment on this issue - in Transfers.kerml - 'item' is used as an identifier in my understanding - is this correct ?
https://github.com/Systems-Modeling/SysML-v2-Release/blob/9d6c67fcbcbdaf54987491cd82c3bc2a7cfb16a5/sysml.library/Kernel%20Libraries/Kernel%20Semantic%20Library/Transfers.kerml#L49
