### ISSUE TITLE
Primary Expressions concrete syntax in KERML doc

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#17]
In the section 7.4.8.2.2 Primary Expressions, the first concrete syntax is lacking the final '=' on the first line

  PrimaryExpression : Expression
  IndexExpression
  | SequenceExpression
  | PathStepExpression
  | PathSelectExpression
  | FunctionOperationExpression
  | BaseExpression

**Comment by seidewitz** [comment]
Fixed for the 2021-05 release.
