### ISSUE TITLE
Item Flows concrete syntax in KERML doc

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#18]
The first line of the third concrete syntax of the section 7.4.9.2.2 Item Flows is finishing with a colon ':' while it should be an equal sign '='

ItemFlowDeclaration (i : ItemFlow, m : Membership) :
( FeatureDeclaration(i, m)
( 'of'  i.ownedRelationship += ItemFeatureMember
| i.ownedRelationship += EmptyItemFeatureMember )
'from'
| ( isSufficient ?= 'all' )?
i.ownedRelationship += EmptyItemFeatureMember
)
i.ownedRelationship += ItemFlowEndMember 'to'
i.ownedRelationship += ItemFlowEndMember

**Comment by seidewitz** [comment]
Fixed for the 2021-05 release.
