### ISSUE TITLE
Sharing Eclipse Docker image

### ISSUE THREAD

**Issue by kenji-miyake** [Systems-Modeling/SysML-v2-Release#23]
Hello, thank you for developing this great project! :smile: 

Seeing [the install manual](https://github.com/Systems-Modeling/SysML-v2-Release/tree/master/install), I felt it's better to have docker images.
As I found a Jupyter image [here](https://github.com/gorenje/sysmlv2-jupyter-docker), I've added an Eclipse one. https://github.com/kenji-miyake/sysml-v2-docker
Could you kindly review this, please?

Besides, this means [command-line installation is supported](https://github.com/kenji-miyake/sysml-v2-docker/blob/c22d07566fb83eb1a421db16ece7485f78a55860/Dockerfile.eclipse#L33-L40).
So, it can simplify the installation steps and improve usability, even when we don't use the Docker image and locally install Eclipse.

Thank you.

**Comment by kenji-miyake** [comment]
To test this, I prepared a sample repository. https://github.com/kenji-miyake/sample-sysml-project

## Setup

```sh
# Use `docker` commands without `sudo`
sudo gpasswd -a $(whoami) docker

# Access display from Docker containers
xhost +local:
```

## Run

```sh
git clone git@github.com:kenji-miyake/sample-sysml-project.git
cd sample-sysml-project
docker run --rm -it --net host -e DISPLAY -v $(pwd):/project ghcr.io/kenji-miyake/sysml-v2-docker/eclipse:latest
```

**Comment by himi** [comment]
Looks interesting.  I’m now too busy to try it out for now but I took a glance at the docket script.  It worth releasing SysMLv2 in P2 repo as well.
One caveat is it’s using X window GUI.  Did you test it under WSL environment?

**Comment by kenji-miyake** [comment]
> Looks interesting. I’m now too busy to try it out for now but I took a glance at the docket script. It worth releasing SysMLv2 in P2 repo as well.

Thank you! :+1: 
btw, what does `P2` means? :thinking:

> One caveat is it’s using X window GUI. Did you test it under WSL environment?

No, not yet, but I've tested with other images.
I believe you can use `VcXsrv`.

**Comment by himi** [comment]
P2 is a provisioning platform Eclipse/Equinox uses.  For details, see the Equinox page.
http://wiki.eclipse.org/Equinox/p2

I'm deploying PlantUML-SysMLv2 in P2 repo while SysMLv2 has not.  By extending Travis-CI script, we could do that.  

Regarding WSL, I expect the technology below would work.  If it's possible, many users will be able to easily install the environment.
https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

**Comment by seidewitz** [comment]
Kenji,

As you noted, Gerrit Riessen has created a Docker image for the SysML v2 Jupyter installation. Tim Weilkeins has also build a demo lab environment on that, publicly available at [](https://www.sysmlv2lab.com/).

While a Docker image for the Eclipse installation is also of interest, given our limited resources, it is not a priority to integrate this into the pilot implementation at this time. However, if you would like to contribute your work to the community, as Gerrit did, that would be much appreciated.

I have approved your membership in the [SysML v2 Release](https://groups.google.com/g/sysml-v2-release) Google group. Please post to that group to move the conversation there.

Thanks.

Ed

**Comment by kenji-miyake** [comment]
@seidewitz Yes, it's fine. I just wanted to share my work, so I'll keep this as my repository for a while.
When you get interested in this in the future, I'm glad to contribute. :smile:

**Comment by kenji-miyake** [comment]
@himi Thank you for your explanation!

> P2 is a provisioning platform Eclipse/Equinox uses. For details, see the Equinox page.

I see. I'll learn more.

> Regarding WSL, I expect the technology below would work. If it's possible, many users will be able to easily install the environment.
https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

Yes, exactly.
Recently, it seems MS is drastically improving GUI environment on WSL. :smile: 
I'll catch up and try it.
