### ISSUE TITLE
Have the source of the PDF document available here

### ISSUE THREAD

**Issue by claell** [Systems-Modeling/SysML-v2-Release#29]
Ideally, remarks and suggestions to the spec could be made directly in the source document (like a LaTeX file). This would also allow PRs to suggest changes.

The current workflow seems ironically pretty document centric to me - the opposite of what SysML tries to achieve, if I understand the scope correctly.

**Comment by seidewitz** [comment]
The source for the specification documents is maintained using the [OpenMBEE](https://openmbee.org) platform. The structure of the documents are generated from an extended SysML v1 view model using the OpenMBEE Model Development Kit plugin for the MagicDraw tool. The model diagrams and class documentation are entirely generated into the document structure from our model repository, while additional text is edited into the document using the on-line OpenMBEE View Editor. 

This modeling and documentation infrastructure is currently only available internally to the SST. The PDF documents are generated for external release.

**Comment by claell** [comment]
Thanks for the insights, I wasn't aware of that.

Still, I'd say that the review process is not ideal (for example, software development on platforms like GitHub seems to have more integrated workflows).

For reference: https://www.openmbee.org/# (the link above did not work for me).
