### ISSUE TITLE
Are the keywords "doc" and "require" for requirements defined somewhere?

### ISSUE THREAD

**Issue by claell** [Systems-Modeling/SysML-v2-Release#31]
Reading the documentation for requirements, I came across the keywords (or something like that) "doc" and "require". Is their usage specified somewhere? If not, what do they mean? Can one use different words instead?

Example from https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/Intro%20to%20the%20SysML%20v2%20Language-Graphical%20Notation.pdf:
![grafik](https://user-images.githubusercontent.com/6171135/126813760-1cba321b-b85d-4c89-8252-7e176c4bda88.png)

**Comment by claell** [comment]
I assume that "doc" is defined in 7.2.2.2.1.2 Documentation of https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/2-OMG_Systems_Modeling_Language.pdf? And "require" seems to be introduced in 7.18.2.1.1 Requirement Definitions.

**Comment by seidewitz** [comment]
You have found the correct references. Our intent is to provide more detailed language description of both the textual and graphical notations for SysML v2 for inclusion in the next revised submission to OMG, due at the end of August.

I would also encourage you to submit language questions such as this to the [SysML v2 Release Google Group](https://groups.google.com/g/sysml-v2-release), which allows for wider community discussion. If you have a Google account, you can request to join the group. Please provide your name and affiliation when you do so.

**Comment by claell** [comment]
Alright.

I submitted a request to join the Google Group now. Personally, I prefer to keep artifacts and code together with related issues, as this seems to make communication easier. Also, I am more used to GitHub (or other similar platforms).

Closing the issue, then.
