### ISSUE TITLE
Almost empty pages in 2-OMG_Systems_Modeling_Language.pdf

### ISSUE THREAD

**Issue by claell** [Systems-Modeling/SysML-v2-Release#32]
The document https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/2-OMG_Systems_Modeling_Language.pdf contains almost empty pages for sections like 7.2.3.2.2.1 Packages.
![grafik](https://user-images.githubusercontent.com/6171135/126815260-7492c55b-4084-4bae-9579-22cb2c29750b.png)

I assume this is unwanted, at least it makes reading the document less pleasant.

**Comment by seidewitz** [comment]
This is an artifact of how these documents are being generated, and the current use of tables to box the BNF text. We are planning on some reformatting of the document leading up to the revised submission in August, but dealing with remaining document generation issues will not really be a priority until our final submission, currently expect in March 2022.
