### ISSUE TITLE
Width of code box in 2-OMG_Systems_Modeling_Language.pdf is not consistent

### ISSUE THREAD

**Issue by claell** [Systems-Modeling/SysML-v2-Release#33]
The code box for 7.2.3.2.2.2 Memberships in https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/2-OMG_Systems_Modeling_Language.pdf contains almost empty pages for sections like 7.2.3.2.2.1 Packages is not consistent regarding its width with the other boxes:
![grafik](https://user-images.githubusercontent.com/6171135/126815521-3dee3a14-7b64-4e57-b408-f8b1acc62414.png)

**Comment by claell** [comment]
This seems to also be the case for other boxes (less prominent) and for some tables.

**Comment by seidewitz** [comment]
These boxes are automatically generated to normally span from margin to margin. However, if there is a line that extends beyond the right margin, then the box is expanded. We expect that there will be some significant reformatting coming in how the BNF text is presented (especially the graphical BNF). However, it is likely that there will be editorial and formatting issues that remain unresolved until our final submission in March.
