### ISSUE TITLE
Right margin may not be respected in the KerML doc

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#35]
On page 94, the OCL code of the **featureIsEnd** constraint goes well over the right margin of the KerML doc.

The last part of the OCL code should be :

> `owningFeatureMembership.oclIsKindOf(EndFeatureMembership)`

The string '**Membership)**' is not visible, but it can be search for.

The problem may exist in some other places, at least one but probably as a systematic problem that could be fixed by changing some parameters in the PDF formater or the font.

**Comment by seidewitz** [comment]
This constraint no longer exists.
