### ISSUE TITLE
Suspicious sentence in section 7.4.4.3.2 Association of KerML

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#39]
The first sentence of the description of this section is the following:

> An Association is a Relationship and a **Class** to enable classification of links between things (in the universe).

However, the model shows that an Association is a Relationship and a **Classifier**. It looks like a typo.

In the same way, the following paragraph declare correctly the General classes as:
> Relationship
> Classifier

**Comment by seidewitz** [comment]
This will be corrected in the (upcoming) 2021-09 public release.
