### ISSUE TITLE
Issues related to the word 'my' in the documentation

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#4]
In the document "1-Kernel_Modeling_Language_(KerML).pdf" created on 2021-03-24, 15:17:47, on page 13, in the Semantic Conformance paragraph, this sentence that doesn't seem to make sense:

> Models expressed in KerML reuse elements of the KerML model libraries to give them semantics, as shown **my** the horizontal block arrow in Fig. 1.

Also those paragraphs in page 44:

> Subclasses of Namespace **my** define additional Memberships to be included in the set of visible Memberships of that kind of Namespace (for instance, the visible Memberships of a Type also include the public inheritedMembershipsof the Type—see 7.3.2).

> A Namespace can also have ownedMembershipsfor which the memberElementis not owned. The union of the set of unowned memberElementsof ownedMembershipsand the set of memberElements(owned or unowned) of importedMemberships **my** be referred to as the complete set of imported members of the Namespace. The membersof a Namespace comprise at least its ownedMembersand the complete set of its imported members. 

Those sentences lose their sense at the word 'my'. I suspect that a global change in this document resulted in an unpredictable result. I suggest this document be revised for those occurrences of the word 'my'. The last one has some particularities : in the document, there is no physical space before the pronoun; one can miss this occurrence if one search for a whole word. 

There are only three occurrences in this document and no occurrence in the other documents. Obviously this pronoun is not usual in a technical document.

**Comment by seidewitz** [comment]
Thanks for reporting these errors. I believe they are actually separate typos, not the result of a global replace. In the first case, "my" should be replaced with "by", in the other two cases, it should be replaced with "may".

This will be fixed in the next release.

**Comment by seidewitz** [comment]
This is corrected in the 2021-03 release.
