### ISSUE TITLE
Is SysML V2 visualized already? 

### ISSUE THREAD

**Issue by bxhddmdww** [Systems-Modeling/SysML-v2-Release#41]
Is SysML V2 visualized already? My project has not been successfully visualized, can I put a picture to see the visual style and the corresponding sysml code that comes with it?How to display its visual interface in jupyter？

**Comment by seidewitz** [comment]
Yes, there is graphical visualization for SysML v2 available from within Jupyter based on PlantUML, though it is still a prototype at this point. You can visualize a model element using the `%viz`_`elementName`_ magic command. Use `%viz -h` to get help information on this command from within Jupyter.

If you have further questions, posting them to the Google Group at https://groups.google.com/g/sysml-v2-release Google is preferable to creating issues here on GitHub. (You will need to log in with a Google account to request membership in the group.)

**Comment by bxhddmdww** [comment]
![1639920773(1)](https://user-images.githubusercontent.com/81006552/146676690-9b2c2f9f-ced3-4b62-a623-b9f7e1517238.png)
Thanks a lot for your response, can you help me answer this question?I have installed the corresponding version according to the instructions, but my project still cannot display the module on plantUML,the tool i used is eclipse,thanks again.

**Comment by himi** [comment]
Please make sure "Diagrams generated from SysML models" checkbox in "Diagram text providers" preference page is checked.  If that text provider does not exist, please reinstall the proper PlantUML distributed by me is installed.

**Comment by bxhddmdww** [comment]
I reinstalled PlantUML with this url(https://github.com/himi/p2-update-puml-sysmlv2/tree/main/updates)
![1640095976(1)](https://user-images.githubusercontent.com/81006552/146944061-7dba3ab9-2051-4a8e-b2a2-67b971e71512.png)
but "Diagrams generated from SysML models" checkbox still doesnt exsist  in "Diagram text providers" preference page
![1640096071(1)](https://user-images.githubusercontent.com/81006552/146944249-02289c37-774d-434a-804f-ce88ae2c4468.png)
Is my url wrong?

**Comment by himi** [comment]
No, it's correct uri.  Can you upload your plug-in details of plantuml in Eclipse Platform Installation details?  Maybe the old plantuml bundles blocked the installation.
![Screen Shot 2021-12-21 at 5 26 55 PM](https://user-images.githubusercontent.com/10537/147005740-599fa494-d26f-480f-befd-c6ffda0669a4.png)

**Comment by bxhddmdww** [comment]
According to your suggestion, I reinstalled eclipse and it can be displayed now, thank you very much！！
![1640150743(1)](https://user-images.githubusercontent.com/81006552/147040250-a8cf6db9-93e8-476c-b912-dab01867ff7d.png)
