### ISSUE TITLE
Missing diagrams in Kernel Modeling Language, Chapter 8

### ISSUE THREAD

**Issue by mickbaggen** [Systems-Modeling/SysML-v2-Release#43]
Earlier versions of the Kernel Modeling Langage document, Chapter 8 (Model Library) contained diagrams that shows the library elements and their relations. This was very helpful in understanding the library structure. In later versions these diagrams were dropped, It would be appriciated if these diagrams can be restored.

**Comment by seidewitz** [comment]
The Kernel Library models are KerML models. There is currently no normative graphical notation for KerML (the focus has been on graphical notation for SysML v2). The diagrams previously included for KerML library models were mocked up in UML and were, hence, not normative. As the library models used more and more KerML features not easily representable in UML, the diagrams became increasingly hard to update and hence became inaccurate, so we removed them.

Eventually, we may propose a graphical notation for KerML and the tooling to support it. Until then, we did not want to include misleading diagrams in the specification. The ultimate normative representation of the library models is currently the textual notation representations found at 

https://github.com/Systems-Modeling/SysML-v2-Release/tree/master/sysml.library/Kernel%20Library
