### ISSUE TITLE
KML: Features of relation "involves"

### ISSUE THREAD

**Issue by mickbaggen** [Systems-Modeling/SysML-v2-Release#44]
In the document Kernel Modeling Language, Chapter 8 (Model Library), there is an assocation _Involves_ (8.6.2.5) which links two features, _involvedIn_ (Object 8.5.2.5) and _involves_ (Performance 8.6.2.10).

I would propose to change the feature name from involves to involved. This has two advantages:
1. No more confusion between the association name _involves_ and the feature name _involves_;
2. A closer correspondance with natural language, stating that "an object is _involved_ in a performance"

**Comment by seidewitz** [comment]
The actual names of these features as given in the declaration for `Involves` in the Performances.kerml file are `involvedObject` and `involvingPerformance`. The document will be updated to reflect this.

(See https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/sysml.library/Kernel%20Library/Performances.kerml.)
