### ISSUE TITLE
KML: missing elements in figure 3 (7.1.4)

### ISSUE THREAD

**Issue by mickbaggen** [Systems-Modeling/SysML-v2-Release#46]
In the KML document (release 2021-12), par. 7.1.4 (KerML Element Hierarchy), the following elements are not shown:
1) FeatureReferenceExpression :> Expression;
2) OperatorExpression :> InvocationExpression;
3) PathStepExpression :> OperatorExpression;
4) PathSelectExpression :> OperatorExpression;

Please add them to the figure for completeness.

**Comment by seidewitz** [comment]
This should be fully corrected now in release 2022-02.
