### ISSUE TITLE
Season of Docs 2022

### ISSUE THREAD

**Issue by capsulecorplab** [Systems-Modeling/SysML-v2-Release#48]
[Season of Docs](https://developers.google.com/season-of-docs) is a Google sponsored program that connects open-source organizations with technical writers to improve documentation. Applications for open-source organizations are open between February 23 - March 25 for 2022, as per their [timeline](https://developers.google.com/season-of-docs/docs/timeline). Could be a good opportunity for SysML v2 to validate its documentation.

**Comment by seidewitz** [comment]
I looked into this, and it seemed like an interesting possibility. But it seemed to take some effort to apply, and I wasn't able to find the time.
