### ISSUE TITLE
KerML v1.0 Conjugation: replace specialization with conjugation

### ISSUE THREAD

**Issue by bertilmuth** [Systems-Modeling/SysML-v2-Release#49]
In clause 7.3.2.2.3 Conjugation, there's the following sentence:

If no humanId or name is given, then the keyword **specialization** may be omitted.

This is apparently a copy&paste error from a different chapter. The sentence should be:

If no humanId or name is given, then the keyword **conjugation** may be omitted.

**Comment by seidewitz** [comment]
Thanks. This will be fixed in the next release.

**Comment by seidewitz** [comment]
Fixed in the 2022-03 release.
