### ISSUE TITLE
Word delimitation in doc when the "code' font is used

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#5]
In the document "1-Kernel_Modeling_Language_(KerML).pdf" created on 2021-03-24, 15:17:47 and the corresponding 2-OMG_Systems_Modeling_Language_(SysML).pdf:

When the 'code' font is used for a word in a regular paragraph, there may be no space or any separator with the following word. For example, on page 78 of the (SysML) doc, the last paragraph is :

> In addition to the standard TextualRepresentaion languagenames defined for KerML, a conformant SysML 
modeling tool shall also recognize the language name "sysml" (ignoring case), in which case the bodytext of the TextualRepresentation shall be a legal representation of the annotatedElementin the SysML textual concrete syntax as defined in this specification.

The 7th word looks like a single word when copied here (languagenames), but visually in the PDF, it looks like two words because 'language' is in the 'code' font and 'names' is in the regular Times Roman. This is disturbing mainly when you search for a whole word (language or names) because 'languagenames' won't show up.

This phenomenon is common in both PDF documents.

**Comment by seidewitz** [comment]
This seems to be an issue with the rendering of the PDF in your viewer. When I view the documents in Apple Preview or Adobe Acrobat Reader, I do see spaces between words in the different fonts. And, when I copy the same paragraph as you did, I get:

>In addition to the standard TextualRepresentaion language names defined for KerML, a conformant SysML modeling tool shall also recognize the language name "sysml" (ignoring case), in which case the body text of the TextualRepresentation shall be a legal representation of the annotatedElement in the SysML textual concrete syntax as defined in this specification.

Note the space between "language" and "names".

**Comment by domroy** [comment]
You're absolutely right. I tried on Windows with a different PDF viewer and the problem don't exist.
Thanks a lot for having taken the time. I will report it to the faulty PDF viewer manufacturer.
