### ISSUE TITLE
Textual syntax

### ISSUE THREAD

**Issue by dhakehurst** [Systems-Modeling/SysML-v2-Release#52]
This is a great addition the SysML,
Many use cases for wanting a textual syntax.
However, three thoughts.
1) has the textual language undergone any kind of "usability" testing? Common problem with many DSLs, no one thinks about the usability of the language.
 - e.g. I don't think that notations such as 'X :> Y' are very usable - might my be my opinion
 - try applying something like Cognitive Dimensions [https://en.wikipedia.org/wiki/Cognitive_dimensions_of_notations]
 
2) Identification numbers. Is it possible to write a model in this syntax as a list of separate statements, each with their own ID number?
 - maybe that would require a different syntax - uncertain - I would have thought it should be possible to combine.
 - e.g. instead of the '{' '}' - use a keyword 'contains'
 - more verbose, but allows for the model to be created from a set of single line, identifiable, statements
 
3) trace links. A little like comments, you want to be able to add them anywhere. I did not see any syntax for adding trace links.
  - something like:
  -- trace as <link-type> to <identity-of-something-else>
  -- trace as 'depends-on' to 'top.subpart.subsubpart'

**Comment by seidewitz** [comment]
There has been several rounds of both formal and informal usability testing. The evolving textual notation has actually been in use by a growing community over the last few years, and we have received a lot of feedback from that. 
Nevertheless, as always, the current notation is the result of a lot of tradeoffs between different concerns, and there are some known usability issues (though, as you seem to realize, not everyone agrees on what the most serious issues are!).

At this time, we are making a push toward a final submission of the proposed specifications to the OMG on February 20, and there are several organizations that are now working on commercial implementations the language based on the draft specifications. Therefore, we have decided to essentially baseline the KerML and SysML notations as of the 2022-11 release, and we have instituted an internal change review process for making only critical changes in the remaining three releases until the final submission.

However, after we make our submission and it is adopted by OMG as "beta specifications", there will be a formal process for submitting issues from the public for consideration by the relevant OMG Finalization Task Force. I would encourage you to submit your suggestions at that time, the I expect that there will be some caution with making any significant changes to the notation during the finalization period.
