### ISSUE TITLE
KerML specification document bad example in 7.2.5.2 Namespace Declaration

### ISSUE THREAD

**Issue by off-my-lawn** [Systems-Modeling/SysML-v2-Release#57]
The latest documentation release includes the following example in KerML section 7.2.5.2 Namespace Declaration:

```
namespace N5 {
  class A;
  comment Comment1 about A
    /* This is a comment about class A. */

  comment Comment 2
    /* This is a comment about namespace N9. */

  /* This is also a comment about namespace N9. */

  doc N9_Doc
    /* This is documentation about namespace N9. */
}
```

It appears that 'Comment 2' should be 'Comment2'.

**Comment by seidewitz** [comment]
Thank you. This has been noted for future correction. (In addition, the comments should be referring to namespace `N5`, not `N9`.)
