### ISSUE TITLE
Eclipse Implementation - no comment highlighting

### ISSUE THREAD

**Issue by EldrML** [Systems-Modeling/SysML-v2-Release#58]
Having played around with this for a while, I'm finding that  within Eclipse IDE 2022-09 (DSL & Java Package version), no `sysml` files seem to have greentext for comments. The keywords are bolded and colored appropriately, so I am confused what is going wrong--it almost seems like the comments `//` and `/* */` aren't being detected for some reason.

I am very much a beginner to Eclipse, xtext, etc, so if there is any simple thing I've missed during the installation path, it wouldn't be the first time.

**Comment by seidewitz** [comment]
You didn't miss anything. Somewhere along the way, the green highlighting stopped working in our editors. I'm not sure why, and it hasn't really been a priority to fix.

Note, though, that in the SysML v2 notation, there is an important difference between "notes", written using `//` or `//* ... */` and "comments" using `/* ... */`. Notes are like lexical comments in programming languages – they are simply ignored like whitespace and not parsed. A comment, on the other hand, is actually a model element and is parsed into the abstract syntax tree, like comments in SysML v1 and UML. A comment can even have a name:
```
comment aComment /* comment text */
```
So it might make sense to eventually get the green text back for notes, but probably not for comments.

**Comment by EldrML** [comment]
That makes sense: with that contextualization, I was referring more specifically to notes highlighting, rather than comments.

Thank you!

**Comment by seidewitz** [comment]
This is fixed in the [2023-02 Release](https://github.com/Systems-Modeling/SysML-v2-Release/releases/tag/2023-02).
