### ISSUE TITLE
Eclipse freezes on autocomplete inside Packages

### ISSUE THREAD

**Issue by bedo2991** [Systems-Modeling/SysML-v2-Release#6]
Every time I try autocompleting (CTRL+SPACE) any text inside a package in a .sysml file, Eclipse freezes.

Autocomplete works when the file is completely empty or when used outside of a package.

Eclipse 2021-03, jdk-11.0.8, Xtext 2.25.0.v20210301-1429
Eclipse log: [log.txt](https://github.com/Systems-Modeling/SysML-v2-Release/files/6216184/log.txt)
Eclipse configuration: [EclipseConfiguration.txt](https://github.com/Systems-Modeling/SysML-v2-Release/files/6216193/EclipseConfiguration.txt)

**Comment by gSeaVelo** [comment]
I have the same issue. But autocomplete inside any context (e..g a bare block def

block Spam {
    bl<CTRL+SPACE here causes hang>
}

) causes a hang. 

I tried reinstalling the plugin (+ PlantUML support) before I found this issue (that didn't fix it). 

Eclipse 2020-12, java.version=15.0.1
running the plugin from the current master of the public repo (SysML-v2-Release) - the pre-built site
[eclipse.log](https://github.com/Systems-Modeling/SysML-v2-Release/files/6218266/eclipse.log)
[eclipseConfig.txt](https://github.com/Systems-Modeling/SysML-v2-Release/files/6218267/eclipseConfig.txt)

**Comment by gSeaVelo** [comment]
Note that building from source (following the instructions at:
https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation
using the current version has the same effect. 

The stack trace looks like: (see attached file for where in the method it's looping
org.eclipse.equinox.launcher.Main at localhost:43773	
	Thread [main] (Suspended)	
		owns: DerivedStateAwareResource  (id=166)	
		Unsafe.park(boolean, long) line: not available [native method]	
		LockSupport.park(Object) line: 175	
		FutureTask<V>.awaitDone(boolean, long) line: 429	
		FutureTask<V>.get() line: 191	
		ContentAssistContextFactory.doCreateContexts(int) line: 181	
		ContentAssistContextFactory.create(String, ITextRegion, int, XtextResource) line: 131	
		DelegatingContentAssistContextFactory$StatefulFactory.doCreateContexts(int) line: 93	
		DelegatingContentAssistContextFactory$StatefulFactory.create(ITextViewer, int, XtextResource) line: 79	
		DelegatingContentAssistContextFactory.create(ITextViewer, int, XtextResource) line: 56	
		CompletionProposalComputer.createContentAssistContexts(XtextResource) line: 68	
		CompletionProposalComputer.exec(XtextResource) line: 50	
		CompletionProposalComputer.exec(Object) line: 1	
		OutdatedStateManager.exec(IUnitOfWork<R,P>, P) line: 70	
		XtextDocument$XtextDocumentLocker.internalReadOnly(IUnitOfWork<T,XtextResource>, boolean) line: 525	
		XtextDocument$XtextDocumentLocker.priorityReadOnly(IUnitOfWork<T,XtextResource>) line: 489	
		XtextDocument.priorityReadOnly(IUnitOfWork<T,XtextResource>) line: 145	
		XtextContentAssistProcessor.computeCompletionProposals(ITextViewer, int) line: 77	
		ContentAssistant$2.lambda$0(ITextViewer, int, List, IContentAssistProcessor) line: 2015	
		1043227965.accept(Object) line: not available	
		Collections$SingletonSet<E>.forEach(Consumer<? super E>) line: 4769	
		ContentAssistant$2.run() line: 2014	
		SafeRunner.run(ISafeRunnable) line: 45	
		ContentAssistant.computeCompletionProposals(ITextViewer, int) line: 2011	
		CompletionProposalPopup.computeProposals(int) line: 573	
		CompletionProposalPopup.lambda$0(boolean) line: 503	
		771844560.run() line: not available	
		BusyIndicator.showWhile(Display, Runnable) line: 72	
		CompletionProposalPopup.showProposals(boolean) line: 498	
		ContentAssistant.showPossibleCompletions() line: 1825	
		XtextSourceViewer(SourceViewer).doOperation(int) line: 978	
		XtextSourceViewer(ProjectionViewer).doOperation(int) line: 1466	
		ContentAssistAction.lambda$0() line: 85	
		70629131.run() line: not available	
		BusyIndicator.showWhile(Display, Runnable) line: 72	
		ContentAssistAction.run() line: 84	
		ContentAssistAction(Action).runWithEvent(Event) line: 474	
		ActionHandler.execute(ExecutionEvent) line: 121	
		E4HandlerProxy.execute(IEclipseContext, Map, Event, IEvaluationContext) line: 97	
		NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
		NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
		DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
		Method.invoke(Object, Object...) line: 498	
		MethodRequestor.execute() line: 58	
		InjectorImpl.invokeUsingClass(Object, Class<?>, Class<Annotation>, Object, PrimaryObjectSupplier, PrimaryObjectSupplier, boolean, boolean, boolean) line: 319	
		InjectorImpl.invoke(Object, Class<Annotation>, Object, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 253	
		ContextInjectionFactory.invoke(Object, Class<Annotation>, IEclipseContext, IEclipseContext, Object) line: 173	
		WorkbenchHandlerServiceHandler(HandlerServiceHandler).execute(ExecutionEvent) line: 156	
		Command.executeWithChecks(ExecutionEvent) line: 488	
		ParameterizedCommand.executeWithChecks(Object, Object) line: 487	
		HandlerServiceImpl.executeHandler(ParameterizedCommand, IEclipseContext) line: 213	
		KeyBindingDispatcher.executeCommand(ParameterizedCommand, Event) line: 308	
		KeyBindingDispatcher.press(List<KeyStroke>, Event) line: 584	
		KeyBindingDispatcher.processKeyEvent(List<KeyStroke>, Event) line: 653	
		KeyBindingDispatcher.filterKeySequenceBindings(Event) line: 443	
		KeyBindingDispatcher.access$2(KeyBindingDispatcher, Event) line: 386	
		KeyBindingDispatcher$KeyDownFilter.handleEvent(Event) line: 96	
		EventTable.sendEvent(Event) line: 89	
		Display.filterEvent(Event) line: 1846	
		StyledText(Widget).sendEvent(Event) line: 1422	
		StyledText(Widget).sendEvent(int, Event, boolean) line: 1449	
		StyledText(Widget).sendEvent(int, Event) line: 1432	
		StyledText(Widget).sendKeyEvent(int, long) line: 1473	
		StyledText(Widget).gtk_key_press_event(long, long) line: 837	
		StyledText(Control).gtk_key_press_event(long, long) line: 3933	
		StyledText(Composite).gtk_key_press_event(long, long) line: 855	
		StyledText(Widget).windowProc(long, long, long) line: 2257	
		StyledText(Control).windowProc(long, long, long) line: 6659	
		Display.windowProc(long, long, long) line: 5919	
		GTK.gtk_main_do_event(long) line: not available [native method]	
		Display.eventProc(long, long) line: 1486	
		OS.g_main_context_iteration(long, boolean) line: not available [native method]	
																																																	Thread [Active Thread: Equinox Container: a13457c3-3345-4088-9809-a3be1fa14799] (Running)	
	Daemon Thread [SCR Component Actor] (Running)	
	Daemon Thread [Framework Event Dispatcher: Equinox Container: a13457c3-3345-4088-9809-a3be1fa14799] (Running)	
	Daemon Thread [Start Level: Equinox Container: a13457c3-3345-4088-9809-a3be1fa14799] (Running)	
	Daemon Thread [Bundle File Closer] (Running)	
	Thread [Gogo shell] (Running)	
	Thread [Worker-JM] (Running)	
	Daemon Thread [EMF Reference Cleaner] (Running)	
	Daemon Thread [Git Repository Closer] (Running)	
	Daemon Thread [Java indexing] (Running)	
	Daemon Thread [Thread-9] (Running)	
	Daemon Thread [com.google.inject.internal.util.$Finalizer] (Running)	
	Daemon Thread [EventAdmin Async Event Dispatcher Thread] (Running)	
	Thread [Worker-6] (Running)	
	Thread [pool-3-thread-1] (Running)	
	Thread [Worker-9] (Running)	
	Thread [pool-4-thread-1] (Running)	
	Thread [pool-2-thread-1] (Running)	
	Thread [pool-2-thread-2] (Running)	
	Thread [Worker-13] (Running)	
	Thread [Timer-2] (Running)	
<img width="694" alt="Screenshot 2021-03-28 202013" src="https://user-images.githubusercontent.com/67664079/112782953-0cdc5500-9003-11eb-8308-e0f6ee125c13.png">

**Comment by seidewitz** [comment]
It is a known problem that content assist does not work. Previous analysis indicated that this was because the default Xtext implementation of content assist results in out special-purpose name resolution algorithm essentially searching the entire global namespace, which takes a very long time. 

With SysML v2 still under development as a language, it has not been a priority to develop a special-purpose content assist implementation. However, we did previously disable the search (effectively also disabling content assist), in order to avoid the kind of lock-up you are seeing. We can determine why the problem is now recurring. But content assist should be avoided in any case.

**Comment by seidewitz** [comment]
Content assist has been fully disabled in the 2021-12 release.
