### ISSUE TITLE
Systems Modeling Application Programming Interface (API) and Services - Release 2023-02 - mistakes?

### ISSUE THREAD

**Issue by samatrhea** [Systems-Modeling/SysML-v2-Release#65]
Dear Submission team,

While reading through Release 2023-02 of the `Systems Modeling Application Programming Interface (API) and Services.pdf` i think the following is incorrect:
  - page 72: **Branch**: owningProject is the Project that owns the given Branch -> this property should not be described here as Branch is a subclass of CommitReference which already has a property called `owningProject`
  - page 72: **Tag**: owningProject is the Project that owns the given Tag-> this property should not be described here as Tag is a subclass of CommitReference which already has a property called `owningProject`

**Comment by seidewitz** [comment]
Sam,

Since the specifications have now been submitted to OMG, any update to them has to be done as part of the OMG finalization process. Please submit issues such as this to the OMG Systems Modeling API and Services Finalization Task Force at https://issues.omg.org/issues/lists/sysmod-api-ftf.
