### ISSUE TITLE
Typo in Documentation - Intro to the SysML v2 Language-Textual Notation

### ISSUE THREAD

**Issue by pjljvandelaar** [Systems-Modeling/SysML-v2-Release#66]
Dear Developers,

On page 8 of Intro to the SysML v2 Language-Textual Notation is written
'''
alias Torque for ISO::TorqueValue;
'''
This should be
'''
alias Torque for ISQ::TorqueValue;
'''

Similar mistake is already solved on slide 7: 'Last changed: 2022-08 (corrected “ISO” to “ISQ”)'

Greetings,
 Pierre

**Comment by seidewitz** [comment]
This was corrected in the 2023-07 version of the material. Thank you for identifying this error.
