### ISSUE TITLE
Typo - Intro to the SysML v2 Language-Textual Notation

### ISSUE THREAD

**Issue by pjljvandelaar** [Systems-Modeling/SysML-v2-Release#69]
Hi Developers,

I think I spotted a typo on slide 70 of "Intro to the SysML v2 Language-Textual Notation" related to simpl(e)Mass.

The definition is without e: "attribute simplMass :> ISQ::mass;"
Yet both references are with "e":
*  "attribute :>> totalMass = simpleMass;"
* "attribute :>> totalMass = simpleMass + sum(subcomponents.totalMass);"

Hopes this helps to make the documentation even better!

Pierre

**Comment by seidewitz** [comment]
This was been corrected in the 2023-07 version of the material. Thanks for identifying this error.
