### ISSUE TITLE
Run into Error following the SysML-v2-Release/install/eclipse/Readme.md

### ISSUE THREAD

**Issue by cptncoolbread** [Systems-Modeling/SysML-v2-Release#7]
Hi,

as a student I tried to install your plugin an run into an error while following the readme instructions

Step 0. for **Installing PlantUML graphical visualization** needs the hint to uncheck **Contact all update sites during install to find required software**

If this checkbox is checked you get an error saying **no repository found containing: osgi.bundle,net.sourceforge.plantuml.eclipse,1.1.25.202103040215**

After unchecking it works fine!

![image](https://user-images.githubusercontent.com/24939201/114600904-2c2ae180-9c95-11eb-82b9-ce4351cbc38b.png)

**Comment by himi** [comment]
I could not reproduce this problem in my environment.  The bundle, osgi.bundle,net.sourceforge.plantuml.eclipse,1.1.25.202103040215, is also included in the repository.  So, the error message you encountered contradicts it.  Can you try to reproduce the same problem?

**Comment by seidewitz** [comment]
@cptncoolbread 
There has been no further update on this issue for some time. Unless you would like to follow up further, I will close issue.
