### ISSUE TITLE
How to define parallel activities in SysML v2?

### ISSUE THREAD

**Issue by pjljvandelaar** [Systems-Modeling/SysML-v2-Release#70]
Dear Developers,

In SysML v2, I can define an action that executes a fixed number of (sub)actions as follows:
```
package Subprocesses {
    import ScalarValues::Integer;

    action Subprocess {in index : Integer;

    }

	action Process {in nr : Integer;
        for i in 1..nr {
            perform Subprocess[i];
        }
    }
}
```

In UML, I can specify (sub)actions using the Expansion Region and indicate using the keywords "iterative", "parallel", and "stream" how  these (sub)actions must be scheduled. For more details, see section Expansion Region of https://sparxsystems.com/resources/tutorials/uml2/activity-diagram.html and https://www.site.uottawa.ca/~tcl/gradtheses/mnojoumian/ThesisFiles/FinalSpec/UML/12.3.27.html.

I however was unable to find how to specify in SysML v2 that these (sub)actions can run in parallel (and not necessarily in sequence).

Is this supported by SysML v2?
If so, could you indicate where it is documented?
If not, what needs to be done to include this feature in the standard?

Greetings,

Pierre

**Comment by seidewitz** [comment]
Please post questions like this to the [SysML v2 Release](https://groups.google.com/g/sysml-v2-release) Google Group.
