### ISSUE TITLE
Missing documentation: A variable capturing whether being in a state

### ISSUE THREAD

**Issue by pjljvandelaar** [Systems-Modeling/SysML-v2-Release#71]
Dear Developers,

After defining a state machine, 
I would to add constraints that check that an instance of such a state machine being in a particular state.

For example, given the following state machine and instance
```
state def StateDef {
	state aState;
}

state myStateInstance : StateDef;
```
I would like to define a precondition that checks that `myStateInstance` is in the `aState`.

An option seems to be
```
requirement def myPrecondition {
	require constraint { myStateInstance.aState}
}
```
However, the `StateUsage` data structure seems more complex than a boolean (and I am unable to find the conversion to boolean function). 
Is this indeed the function I am looking for?
If not, could you point me to the right function / keyword? 

Furthermore, could the documentation of state machines be extended with explaining how to check that the state machine is in a particular state?

Thanks in advance,
   Pierre

P.S. I can add such functionality by adding a boolean variable for each relevant state, but that seems not productive.

**Comment by bertilmuth** [comment]
You might find this information helpful: 
[SysML v2 Release Google Group - Transfer of state information between parts](https://groups.google.com/g/sysml-v2-release/c/dbT4uuHA2iM/m/MuGa6gCuEQAJ)
