### ISSUE TITLE
Enhance documentation about state def abstraction

### ISSUE THREAD

**Issue by pjljvandelaar** [Systems-Modeling/SysML-v2-Release#74]
Hi SST,

As a designer, I would like to reuse known patterns as much as possible.
In particular, I would like to make an abstract state def, and use it for all state defs that exhibit the same behaviour.
Of course, the exact events that trigger state transitions probably are different!

However, from the documentation it is not clear, how to specify this.

For example, a radio and a navigation are two electronic devices (in a car): both can be turned on and off.

Would the following be sufficient to realize the desired behaviour, or will `radioStates` not accept `RadioOnSignal`s?
```
    /* Electronic Device (Abstract) */
    abstract state def ElectronicDeviceStates {
        abstract attribute def OnSignal;
        abstract attribute def OffSignal;
        
        entry; then off;

        state off;
            accept OnSignal
                then on;

        state on;
            accept OffSignal
                then off;        
    }

    /* Radio */
    state radioStates : ElectronicDeviceStates {
        attribute def RadioOnSignal :> OnSignal;
        attribute def RadioOffSignal :> OffSignal;
    }

    /* Navigation */
    
    state navigationStates : ElectronicDeviceStates {
        attribute def NavigationOnSignal :> OnSignal;
        attribute def NavigationOffSignal :> OffSignal;
    }
```

Or would I need the following?
```
    /* Electronic Device (Abstract) */
    abstract attribute def OnSignal;
    abstract attribute def OffSignal;

    abstract state def ElectronicDeviceStates {
        abstract attribute onSignal: OnSignal;
        abstract attribute offSignal: OffSignal;
        
        entry; then off;

        state off;
            accept onSignal : OnSignal
                then on;

        state on;
            accept offSignal : OffSignal
                then off;        
    }

    /* Radio */
    attribute def RadioOnSignal :> OnSignal;
    attribute def RadioOffSignal :> OffSignal;

    state radioStates : ElectronicDeviceStates {
        attribute radioOnSignal : RadioOnSignal redefines onSignal;
        attribute radioOffSignal : RadioOffSignal redefines offSignal;
    }

    /* Navigation */
    attribute def NavigationOnSignal :> OnSignal;
    attribute def NavigationOffSignal :> OffSignal;
    
    state navigationStates : ElectronicDeviceStates {
        attribute navigationOnSignal : NavigationOnSignal redefines onSignal;
        attribute navigationOffSignal : NavigationOffSignal redefines offSignal;
    }
```

Please enhance the documentation to help the users of SysML v2 to more easily model their systems!

Greetings,
 Pierre

P.S. You can use the provided examples in your documentation.

**Comment by seidewitz** [comment]
Language specification documents are not tutorial documents, and they need to focus on formally defining and explaining the language in general. However, there is, of course, a separate need to provide additional resources for modelers to learn how to use SysML v2. For now, if you would like to ask questions about using the language, please post them to the [SysML v2 Release]([pjljvandelaar](https://github.com/pjljvandelaar)) Google group (you will need to request membership while logged into a Google account).
