### ISSUE TITLE
sysml2 model using sysml1

### ISSUE THREAD

**Issue by rizickus** [Systems-Modeling/SysML-v2-Release#75]
I assume sysml2 is designed using sysml1. Where can we find sysml2 model based on sysml1?

**Comment by seidewitz** [comment]
SysML v1 was not used to "design" SysML v2. SysML v2 is based on KerML (the Kernel Modeling Language), both of which are specified using the OMG-standard MOF (MetaObject Facility) metamodeling language. This is described in the specifications for KerML and SysML v2.

If you would like to discuss this further, please post an issue to the [SysML v2 Release](https://groups.google.com/g/sysml-v2-release) Google Group (you must first request membership while signed into a Google account).
