### ISSUE TITLE
Textual syntax grammar '2a-OMG_Systems_Modeling_Language.pdf' has lots of errors

### ISSUE THREAD

**Issue by dhakehurst** [Systems-Modeling/SysML-v2-Release#77]
The grammar for the textual syntax described in chapter 8.2.2 of
'2a-OMG_Systems_Modeling_Language.pdf' has lots of errors.

The grammar rules have many mistakes
and they do not match the implementation given in the code.

**Comment by seidewitz** [comment]
Please submit any errors you find as issues at https://issues.omg.org/issues/create-new-issue. You can first check on issues that have already been submitted at https://issues.omg.org/issues/lists/sysml-v2-ftf.
