### ISSUE TITLE
Incorrect syntax in example OR incorrect grammar in KerML

### ISSUE THREAD

**Issue by dhakehurst** [Systems-Modeling/SysML-v2-Release#78]
Example [Vehicle Example/VehicleDefinitions.kerml]

```
package VehicleDefinitions {
	doc
	/*
	 * Example vehicle definitions model.
	 */

	
	/* BLOCKS */
     ^^^^
	class Vehicle;	
	class Transmission;	
```

either a grammar issue and 'doc' element should be allowed multiple REGULAR_COMMENT's in it

OR

in this example`\* BLOCKS *\` (and others later in example) should be a MULTILINE_NOTE not a  REGULAR_COMMENT

not sure why your own tests are not showing this up ?

**Comment by dhakehurst** [comment]
this might be a mistake in the standard grammar where comment is defined as

```
Comment =
  'comment' Identification
  (  'about'  Annotation ( ',' Annotation )*  )?
 REGULAR_COMMENT
```

where as the pilot implementation XText specifies

```
Comment returns SysML::Comment :
	( 'comment' Identification?  ('about'  Annotation  ( ',' Annotation )* )?  )?
	REGULAR_COMMENT
;
```

**Comment by seidewitz** [comment]
This does, indeed, look like an error in the KerML Specification document. Please submit this as an issue at https://issues.omg.org/issues/create-new-issue.

**Comment by seidewitz** [comment]
This has been fixed.
