### ISSUE TITLE
install.bat file error

### ISSUE THREAD

**Issue by fikha101** [Systems-Modeling/SysML-v2-Release#80]
Everytime i run the install.bat file as mentioned in the instructions, i receive the attached error. 
![Screenshot 2023-11-04 162725](https://github.com/Systems-Modeling/SysML-v2-Release/assets/35099518/af9c990f-7c7f-4494-9002-2e4e372af803)

**Comment by seidewitz** [comment]
You most likely did not download the release correctly. You need to either make a Git clone of the SysML-Release repository, or download and unzip the complete archive attached to the release notes. 

If you would like further help, please ask on the https://groups.google.com/g/sysml-v2-release group.
