### ISSUE TITLE
Missing tag <<variation>> on <<part def>> in PlantUML graphical representation

### ISSUE THREAD

**Issue by westboros** [Systems-Modeling/SysML-v2-Release#86]
Installed 2024-02 release and noticed that the \<\<variation\>\> tag is missing on \<\<part def\>\> elements. However, the \<\<variation\>\> tag is visible on \<\<part\>\> elements.

From the SysMLv2 spec, it seems the \<\<variation\>\> should appear on \<\<part def\>\> elements.

From 2a-OMG_Systems_Modeling_Languge.pdf Table 4. Definition and Usage - Representative Notation:

![SysMLv2VariationPartDef](https://github.com/Systems-Modeling/SysML-v2-Release/assets/134856694/afafb80c-9c8b-437b-88d2-cadc3e9cae02)

From my local eclipse project:

![SysMLv2VarationTag](https://github.com/Systems-Modeling/SysML-v2-Release/assets/134856694/3fd9c194-4b8b-40b5-80ca-2d2925d6116e)

**Comment by westboros** [comment]
Perhaps this bit of code in SysML2PlantUMLText.java in org.omg.sysml.plantuml is to blame (line 260):

    private static void appendVariation(StringBuilder sb, Type typ) {
        if (!(typ instanceof Usage)) return;
        Usage u = (Usage) typ;
        if (u.isVariation()) {
            sb.append(" <<variation>>\\n");
        }
    }

Not sure why there is a need to exit the appendVariation() method if typ is not an instance of a Usage.

**Comment by himi** [comment]
I forgot the case that `typ` is of Definition as well as Usage.  I'll fix it.

**Comment by seidewitz** [comment]
This has been fixed.
