### ISSUE TITLE
Incorrect Containment Multiplicity Notation Between Variations and Variants

### ISSUE THREAD

**Issue by westboros** [Systems-Modeling/SysML-v2-Release#87]
I don't believe it makes sense for any containment relationship to have a multiplicity defined on either end. However, there appears to be a default multiplicity of [*] on the target end of containment relationships between \<\<variations\>\> and their \<\<variants\>\>. At least when visualizing these elements using PlantUML.

![Variation-Variant-Containment-Multiplicity](https://github.com/Systems-Modeling/SysML-v2-Release/assets/134856694/f80db207-4ab7-4b23-a883-3f1d6f61d2e8)

**Comment by seidewitz** [comment]
This is no longer the case since release 2024-07.
