### ISSUE TITLE
BodyExpressionMember vs. ExpressionBodyMember

### ISSUE THREAD

**Issue by harttraveller** [Systems-Modeling/SysML-v2-Release#90]
Hi, thanks for the great work on this! Quick question relating to the KerML EBNF meta-model:

On page 100 of the [KerML documentation](https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/1-Kernel_Modeling_Language.pdf) it defines a select expression as the following:

```ebnf
SelectExpression : SelectExpression =
    ownedRelationship += PrimaryArgumentMember '.?'
    ownedRelationship += BodyExpressionMember
```

However as best as I can tell, `BodyExpressionMember` is not defined. `ExpressionBodyMember` is however defined, on page 102:

```ebnf
ExpressionBodyMember : FeatureMembership =
    ownedMemberFeature = ExpressionBody
```

I was thinking this is a typo, and `BodyExpressionMember` should be `ExpressionBodyMember` in the select/collect expressions - but I wanted to double check to confirm. I figured I'd open a GitHub issue so it can be fixed (on the off chance it is a typo).

Thanks for your time!

**Comment by seidewitz** [comment]
Actually, `BodyExpressionMember` should be replaced with `BodyArgumentMember` in both `CollectExpression` and `SelectExpression`. `BodyArgumentMember` is defined in subclause 8.2.5.8.2 along with `CollectExpression` and `SelectExpression`, just below `FunctionOperationExpression`.

Thanks for reporting this issue. However, for future reference, any issues with the specification document should be reported to OMG at https://issues.omg.org/issues/create-new-issue, not on GitHub. Now that the specification has been adopted by OMG, the only way changes can be made is through the formal issue resolution processes. For this time, though, I have created an OMG issue for you: https://issues.omg.org/issues/KERML_-83.

**Comment by harttraveller** [comment]
Thank you @seidewitz - appreciate it the help!
