### ISSUE TITLE
Table 6 Duplicate Row Titles

### ISSUE THREAD

**Issue by feuertier** [Systems-Modeling/SysML-v2-Release#91]
This table has two rows where the Element Column states Enums Compartment. Recommend adding information to the row titles to indicate what aspect of the compartment is important. E.g., Enums Compartment (enumeration usage names) and Enums Compartment (enumeration values). Alternatively, combine these into one row.

**Comment by Weilkiti** [comment]
Hi,

This sounds like a specification issue. You can create an issue here: https://issues.omg.org/issues/create-new-issue

Thanks,
Tim

From: feuertier ***@***.***>
Sent: Tuesday, June 11, 2024 8:46 PM
To: Systems-Modeling/SysML-v2-Release ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Systems-Modeling/SysML-v2-Release] Table 6 Duplicate Row Titles (Issue #91)


This table has two rows where the Element Column states Enums Compartment. Recommend adding information to the row titles to indicate what aspect of the compartment is important. E.g., Enums Compartment (enumeration usage names) and Enums Compartment (enumeration values). Alternatively, combine these into one row.

**Comment by feuertier** [comment]
Thank you!
