### ISSUE TITLE
sysml v2 code can run to get result？

### ISSUE THREAD

**Issue by ayuxjh** [Systems-Modeling/SysML-v2-Release#94]
After a period of learning sysml v2 semantics, I'm very familiar with writing SYSML v2 code on Jupyter Lab and visualizing it at the same time（plantuml）, 
but I'm curious to know if the sysml v2 analysis and validation cases can be run code directly  to get results?

**Comment by seidewitz** [comment]
There is a limited capability implemented to evaluate expressions, but it is not possible to fully execute analysis and verification cases at this time. If you would like to discuss this topic further, please post to the Google group Ihttps://groups.google.com/g/sysml-v2-release.
