### ISSUE TITLE
conda env broken after running ./install.sh for sysml 2 juypter lab, sysml kernal keep restarting

### ISSUE THREAD

**Issue by Zongru-Wang** [Systems-Modeling/SysML-v2-Release#97]
**Hello, I create a new conda env and run the install.sh for both my linux server and macOS, and the conda doesn't work:**

run :: echo $PATH
===== /home/ubuntu/anaconda3/lib/jvm/languages/python/condabin:

**I checked my** 

nano ~/.bashrc
***************************************
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ubuntu/anaconda3/lib/jvm/languages/python/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ubuntu/anaconda3/lib/jvm/languages/python/etc/profile.d/conda.sh" ]; then
        . "/home/ubuntu/anaconda3/lib/jvm/languages/python/etc/profile.d/conda.sh"
    else
        export PATH="/home/ubuntu/anaconda3/lib/jvm/languages/python/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

**And change it to** 

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ubuntu/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ubuntu/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ubuntu/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ubuntu/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

**But got** 

/home/ubuntu/anaconda3/lib/jvm/languages/python/lib/python3.10/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'GraalVM JSSE'.

I can start juypter lab and there is a kernal Named Sysml but when I tried to run the notebook with sysml, the kernal will keep restarting

**Comment by seidewitz** [comment]
If you would like help with resolving Jupyter deployment installation problems, please join the Google group at https://groups.google.com/g/sysml-v2-release and post a topic their. We would prefer not to use GitHub issues for this purpose.
